# Generated by Django 3.1.1 on 2020-09-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App',
            new_name='File',
        ),
    ]
